import style from './admin.module.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AdminLayout({children}) {
  return (
      <div className={style.common_hearding}>{children}</div>
  )
}
