import style from './admin.module.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={style.common_hearding}>{children}</body>
    </html>
  )
}
