import "./globals.css";
import { Roboto } from "next/font/google";
import { Work_Sans } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
});

const workSans = Work_Sans({
    subsets: ["latin"],
    variable: "--font-work-sans"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${workSans.variable}`}
      >
        <h1 className={`text-green-400 ${workSans.className}`}>Hello Guys👋</h1>
      
        {children}
      </body>
    </html>
  );
}
